### ISSUE TITLE
框架

### ISSUE THREAD

**Issue by wangdanjun** [jcyrss/hytest#3]
老师你这个是在什么框架上面优化的吗

**Comment by jcyrss** [comment]
代码没有基于任何框架。 

初始化、清除的理念做法基于robotframework

**Comment by wangdanjun** [comment]
谢谢老师的回复！

**Comment by jcyrss** [comment]
> 老师 怎么让用例按指定的顺序执行呢？

用例目录/用例文件的执行次序由其名字的unicode编码次序决定的。 你可以在前面加上编号， 比如01-功能， 02-功能 . 01开头的就会先执行

同一个用例文件里面的用例执行次序是由用例出现的先后次序决定的


另外很重要的， 如果你用例执行次序颠倒，就会导致执行出问题， 说明你本身用例自动化开发就有大问题。 用例执行次序不应该影响用例的执行结果。你应该通过初始化清除保证用例的执行环境依赖，而不是通过别的用例提供环境依赖

**Comment by Jamesli0123** [comment]
老师好，请问直接拿包解压执行报错是怎么回事呢
F:\hytest-main>hytest

    *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *
    *       hytest 0.8.11            www.byhy.net       *
    *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *



===   [ 收集测试用例 ]  ===


== cases\__st__.py

Traceback (most recent call last):
  File "C:\Users\zhkj\AppData\Local\Programs\Python\Python311\Lib\site-packages\hytest\run.py", line 141, in run
    Collector.run(
  File "C:\Users\zhkj\AppData\Local\Programs\Python\Python311\Lib\site-packages\hytest\utils\runner.py", line 100, in run
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\hytest-main\cases\__st__.py", line 2, in <module>
    from lib.share import  gs
  File "F:\hytest-main\lib\share.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'



!! Collect Test Cases Exception Aborted !!




===   [ 执行测试用例 ]  ===

!! 没有可以执行的测试用例

F:\hytest-main>

**Comment by jcyrss** [comment]
ModuleNotFoundError: No module named 'selenium'  ==== 提示的很清楚， 如果这个报错都看不懂，建议先学好python语言，再学习自动化测试
